apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-app-trainning-namespace
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: nginx-app-trainning-namespace
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2
        ports:
        - containerPort: 80
        env:
        - name: NGINX_HOST
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: nginx_host
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: nginx_port
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-app-trainning-namespace
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001